language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: IrkAzT9kMxcwuZ+oNCn+MB1HCMMPBQWDpz6rlz99HKU0QgUxHinCrdveCf1pY+Lojoqk/VEEv8EmbMSs0yDO33/1x4C1lpV0DrYHt5+tJ1L3qENtInusfMP4LkTCvUc3dGMeOQ7IpZ7WhH3pIhk3VEZ/zF4AJ8iHjGyxeKS/JosKGrrNX5dL+E0v3+NqlPgW+tl6bbwWhrUJSuj4vzTgUqcfC4zjy6F0eO8RzzH4Ewjd1dti1+BFvNrKJV2Wx0iSqeI15Bc5LRPLuTdpuI+2TqBPXh76FeJ3w9i5zyb0JcLLf9sL4suWhQtZfWmYdSMsWbVqfGD/6pltEUdfha7XT6gagPGGkHYv4y8Sm34XuBM3vsvZwVvAUuIBayl45xnJ8MF/KdvK0gF3EDtFAx0bUGlK3qyy3rhvwnwlpaPnBMnx5K4lQkFtbTS8fgrX2SxU/bBBBRFb6Zra6cc6v9Cdsa43SrklhdZlBVQZ1bgm1EsyeMOB0B4xVTalHWXtyX4J6OoQGbFsDPZGOl6X3+IL2GOZSE9kDgVhESIopLY5hfIRVXiM1yAsvmMPyhmyiOfy4RH1rMHdBk/pXm3rCM7rT7FFBm+Ie51oPYkEYAsSRgTrwF/3iRYjttOFmTiToRxWqUbwRpjggKDwGGs98UWfbHkDshLVMifq8dtVRaWIVLY=
  app: blog-app-mongo7515
  on:
    repo: anthonyphoto/blog-app-mongoose-challenge-solution
